### PR TITLE
Add Epic Games HTTP CDNs

### PR DESCRIPTION
**Pull request by GotenXiao**
### What CDN does this PR relate to
Epic Games :tada: 

### Does this require running via sniproxy
No

### Capture method
Vendor supplied

### Testing Scenario
Home instance

### Testing Configuration
`docker-compose.yml`:  
```yaml
version: '2'
services:
  dns:
    image: steamcache/steamcache-dns:localdomains
    env_file: .env
    ports:
      - ${DNS_IP}:53:53/udp
    volumes:
      - ../cache-domains/:/opt/cache-domains/

  sniproxy:
    image: steamcache/sniproxy:latest
    env_file: .env
    ports:
      - 443:443/tcp

  monolithic:
    image: steamcache/monolithic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    ports:
      - ${LANCACHE_IP}:80:80/tcp
```
(Some other minor hacks required on `monolithic` to get the new names in the map file.)  
Downloaded Unreal Tournament through the cache server, reported misses.

### Sniproxy output
```
     33 epicgames-download1.akamaized.net
```
Likely from the launcher download.

### CODE REVIEW

**Comment by Lepidopterist** [comment]
I'd be tempted to make it sniproxy required, to catch the probable Launcher download, otherwise, thumbs up from me.

**Comment by GotenXiao** [comment]
Good catch, will do so.

**Comment by GotenXiao** [comment]
Changed.

**Comment by apnormal** [comment]
can u make one video step by step configure catch server for epic games?

**Comment by Lepidopterist** [comment]
Install a computer with <insert your preferred Linux-based OS here>
Install docker-ce (See your preferred OS documentation)

run the following commands:
```
HOST_IP=`hostname -I | cut -d' ' -f1`
docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=$HOST_IP lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 80:80  lancachenet/monolithic:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 lancachenet/sniproxy:latest
echo Please configure your dhcp server to serve dns as $HOST_IP
```

Then, configure your DHCP server to serve out your Lancache IP as your DNS server.

**Comment by apnormal** [comment]
hello my friend this work for epic games on fortnite

**Pull request merged**
