### PR TITLE
Script Support for RPZ Domains

### PR DESCRIPTION
**Pull request by dhoffend**
We're using a dual bind/ddns setup with dhcp failover. For lancache functions we're using the response policy zone feature of bind to manipulate and filter dns responses.

### CODE REVIEW

**Review by MathewBurnett — CHANGES_REQUESTED** [review]

**Review by MathewBurnett — APPROVED** [review]

**Comment by MathewBurnett** [comment]
Sorry this took so long to get too, however i was very please to discover when i was about to look at writing this that some hero had already finished

**Comment by dhoffend** [comment]
Thanks for the merge. We find the RPZ method very convenient, cause the rpz zone gets replicated across our DNS servers, which makes changes on, the fly during the event, as easy as maintaining our local zone.

**Comment by MathewBurnett** [comment]
I just ran into the first time i wanted to use bind to do it outside the lancache_dns container and realised we didn't have a bind script separately. You have definitely saved me some time so thanks.

**Comment by dhoffend** [comment]
Another use case would be to provide the rpz master zone from within the Container to to the outside world.

 On your local set of bind servers, you can define the rpz zone as slave zone with the master zone served by the lancache container.

**Pull request merged**
