### PR TITLE
Update rockstar.txt

### PR DESCRIPTION
**Pull request by copystring**
For the new Rockstar Games Launcher

**What CDN does this PR relate to**
a84-53-187-48.deploy.static.akamaitechnologies.com for the new Rockstar Games Launcher

**Does this require running via sniproxy**
untested

**Capture method**
Nirsoft TCPLogView

**Testing Scenario**
At home via LAN

### CODE REVIEW

**Comment by MathewBurnett** [comment]
this is a reverse lookup for an akamai cdn ... not a rockstar specific address

**Comment by copystring** [comment]
Right. Sorry.
However the new rockstar launcher does not work with lancache. It does not get any requests from the launcher.
How would I get this right?

**Comment by MathewBurnett** [comment]
first thing to check with the launcher is does it connect on port 80 or 443? I have yet to try it as i have my rockstar games through steam i think

**Comment by copystring** [comment]
It is port 443. I guess we are out then.

**Comment by MathewBurnett** [comment]
if the content download is been done on 443 then it is almost certainly https and not cache compatible

**Comment by MathewBurnett** [comment]
however i'm reasonably sure all their content is available on steam

**Pull request closed without merging**
