### PR TITLE
Add Blizzard CND

### PR DESCRIPTION
**Pull request by yangcaixing**
### What CDN does this PR relate to

"http://client05.pdl.wow.battlenet.com.cn/tpr/hs/data/59/70/59709257fd6b52ca9dab2f96a640f523"
Need Add "battlenet.com.cn" to blizzard.txt
### Does this require running via sniproxy

No
### Capture method

Client download blizzard games, and capture logs.
### Testing Scenario

Client download blizzard games, and capture logs.
### Testing Configuration
```
<!-- Paste either your docker run command from the DNS container OR explain how you have setup DNS zone files etc to test this issue -->
```
docker-compose up -d
### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

### CODE REVIEW

**Comment by riconnon** [comment]
The hostname in your log fragment is `client05.pdl.wow.battlenet.com.cn` which would not be matched by just `battlenet.com.cn` in the list.
I suspect `*.pdl.wow.battlenet.com.cn` would be required at least.

**Comment by yangcaixing** [comment]
> The hostname in your log fragment is `client05.pdl.wow.battlenet.com.cn` which would not be matched by just `battlenet.com.cn` in the list.
> I suspect `*.pdl.wow.battlenet.com.cn` would be required at least.
Yes correct, "battlenet.com.cn" just my DNS server condition forward domain, for Lancache-DNS, it shoud be "*.pdl.wow.battlenet.com.cn".

**Comment by MathewBurnett** [comment]
We are unlikely to add Chinese domains to our standard set, however you are able to use your own domain repo on your lancache setup by adding the environmental variable CACHE_DOMAINS_REPO="https://github.com/your-username/cache-domains.git"

[https://lancache.net/docs/containers/monolithic/cache_domains/ ](https://lancache.net/docs/containers/monolithic/cache_domains/ )

**Comment by yangcaixing** [comment]
> We are unlikely to add Chinese domains to our standard set, however you are able to use your own domain repo on your lancache setup by adding the environmental variable CACHE_DOMAINS_REPO="https://github.com/your-username/cache-domains.git"
> 
> [https://lancache.net/docs/containers/monolithic/cache_domains/ ](https://lancache.net/docs/containers/monolithic/cache_domains/)

Hi Proto,
   Thanks for your suggestion , but when I use my own domain repo, it alway have some errors, I already remove all container, but it still not not works, could you please help with it.  btw, I run lancache works fine with below steps.
"git clone https://github.com/lancachenet/docker-compose lancache
  cd lancache
  nano .env
  docker-compose up -d"

root@steamcache:~# docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=172.20.90.247 -e CACHE_DOMAINS_REPO="https://github.com/yangcaixing/cache-domains.git" lancachenet/lancache-dns:latest
docker: Error response from daemon: Conflict. The container name "/lancache-dns" is already in use by container "74d09b12d60a6a9aa6e1632ac3f8ffbeb627b5e2800890550c6aab3ddab912d3". You have to remove (or rename) that container to be able to reuse that name.

**Comment by yangcaixing** [comment]
> We are unlikely to add Chinese domains to our standard set, however you are able to use your own domain repo on your lancache setup by adding the environmental variable CACHE_DOMAINS_REPO="https://github.com/your-username/cache-domains.git"
> 
> [https://lancache.net/docs/containers/monolithic/cache_domains/ ](https://lancache.net/docs/containers/monolithic/cache_domains/)

Thanks Proto, it works now.

**Comment by VibroAxe** [comment]
Closing due to inability of uklans to support

**Pull request closed without merging**
