### PR TITLE
Reinstate Origin per beta client  10.5.63.37653 - 758549

### PR DESCRIPTION
**Pull request by Lepidopterist**
### What CDN does this PR relate to

Origin
### Does this require running via sniproxy

Yes
### Capture method

EA Staff
### Testing Scenario

Validated by @MathewBurnett , @Crabbey 
### Testing Configuration
```
<!-- Paste either your docker run command from the DNS container OR explain how you have setup DNS zone files etc to test this issue -->
```
Standard Docker implementation
### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

Please HOLD for full client release.

### CODE REVIEW

**Comment by astrolox** [comment]
Are we waiting for Origin?
If so, so we know when will this be ready to merge?

**Comment by unspec** [comment]
Yes, waiting for it to go into live from Beta. No ETA as yet. We think they need to tweak a few things yet.

**Comment by malteserr** [comment]
It seems like the non-beta version of Origin was just updated to 10.5.64.37936 - 758832

**Comment by mintopia** [comment]
Confirmed now in non-beta client.

**Pull request merged**
