### PR TITLE
Create steamcache-unbound.conf

### PR DESCRIPTION
**Pull request by Mikki-10**
Config file for unbound DNS server, generated using a self made PHP script.
Can also be used for pfSense, when using the DNS Resolver (unbound) in the "Custom options" textarea.

### CODE REVIEW

**Comment by Mikki-10** [comment]
Sry not the best commit message

**Comment by mintopia** [comment]
Hi @Mikki-10,

I'm probably going to reject this as a pull request as I don't think we should be having generated configs in here, however - I'm open to the idea of putting the script itself in here, and potentially putting up a website to allow people to generate their own configs.

Would you be OK with doing a separate commit/push with your script in a scripts folder so we can use it as a base for a generator for configs?

Thanks,
Jess

**Comment by Mikki-10** [comment]
Sure np i understand, i can start out on a small script (single webpage that can be easily integrated) where you can choose which config you want, if you like?

**Comment by VibroAxe** [comment]
@mikki-10 from a quick look at your initial commits, you should be backing each of the defined cdns (from the json) onto a unique IP, currently looks like you are mapping everything into the same IP which may result in cache collisions

**Pull request merged**
