### PR TITLE
Only use lancache.steamcontent.com for steam

### PR DESCRIPTION
**Pull request by VibroAxe**
### What CDN does this PR relate to
Remove all non lancache domains from steam. This PR requires https://github.com/lancachenet/monolithic/pull/87 to be implemented before merging (and perhaps some time for people to adopt as well!)

### Does this require running via sniproxy
No

### Capture method
Steam change logs and direct discussions with valve

### Testing Scenario
https://github.com/lancachenet/monolithic/pull/87

### Testing Configuration
https://github.com/lancachenet/monolithic/pull/87#issuecomment-579837241

### Sniproxy output
N/A

### CODE REVIEW

**Comment by VibroAxe** [comment]
Added WIP tag to prevent merging until https://github.com/lancachenet/monolithic/pull/87 is merged

**Comment by unspec** [comment]
@VibroAxe - https://github.com/lancachenet/monolithic/pull/87 has been merged. Worth waiting for the next batch of LANs next week to further test the new steam approach or happy to take this one out of WIP now?

**Comment by VibroAxe** [comment]
I think we should leave this be for the moment, without the ua caching this merge will break the cache for anyone not running latest. I'm thinking give it 2-3 months then merge in?

**Comment by Lochnair** [comment]
Ran into an issue where creating workshop collections won't work because it tries to reach https://ufs0101.steamcontent.com:8699/ugcupload. That obviously can't work when one only have a SNI proxy on port 443.

I assume Valve expects that anything else than lancache.steamcontent.com aren't messed with now. So I ask that you consider merging this PR again to allieviate issues like this.

**Comment by VibroAxe** [comment]
@Lepidopterist @mintopia @MathewBurnett anyone have any thoughts on merging this?

**Comment by mintopia** [comment]
I think we should try merging it and keep an eye on support requests and feedback. It *should* be OK.

**Comment by Lepidopterist** [comment]
Agreed.  It's been a while.

**Comment by miketweaver** [comment]
You update http://diagnostics.lancache.net/ to reflect this change.

**Pull request merged**
