### PR TITLE
Added BOINC based projects

### PR DESCRIPTION
**Pull request by adamradocz**
I added the addresses of BOINC based projects.
It's not game related, I hope it's fine.

### CODE REVIEW

**Comment by Lepidopterist** [comment]
Hey adamradocz,

Whilst we do accept PRs for additional domains, this curated list is designed to be of general use to LAN parties, and more specifically bulk downloads. The main reason for this is to save on bandwidth usage when holding events.

Having checked over the list, I'm not convinced of the use of including the new domains that you have suggested, (and some of them are not domains, they are web addresses and thus unsuitable anyway).

Can I ask what you're actually trying to achieve, to see if we can help?

Many thanks

**Comment by adamradocz** [comment]
These projects use multiple machines for distributed computing, and I thought for schools, organizations and maybe homes with multiple PCs would benefit if they could use the caching. Without it every PC has to download the projects files from the project servers.

**Comment by unspec** [comment]
Are there examples of large HTTP downloads from these sites?

For distributed computing won't most of the downloads be unique per client as each client is assigned different "blocks" of data to work on etc?

I'd also be concerned that simply removing www and leaving the top level domain in the list won't necessarily capture the actual hostname that files are being downloaded from for each of these services. We try to specifically list out hostnames that we have seen/verified downloads from, and only list top level domains where that domain is purely used for content distribution.

**Comment by adamradocz** [comment]
The first initialization usually contains bigger files, but after that the downloads would be smaller, so you are right.

**Pull request closed without merging**
