### PR TITLE
Add new CDN for Steam Failback

### PR DESCRIPTION
**Pull request by mintopia**
### What CDN does this PR relate to
Steam

### Does this require running via sniproxy
Yes

### Capture method
N/A

### Testing Scenario
None

### Testing Configuration
N/A

### Sniproxy output
N/A

### CODE REVIEW

**Comment by mintopia** [comment]
Creating a PR to kick off discussion around this topic. Re-adding the Steam domains as a separate CDN to allow people to still intercept them for when Steam stops using the trigger domain and falls back to using the content servers directly.

- Can be disabled in lancache-dns using `DISABLE_STEAMFAILBACK` environment variable
- lancache-monolithic will use the Steam User Agent to identify Steam, so it will be cached alongside Steam

Points for discussion:

- When Steam fails back, it will potentially upgrade back to TLS and prevent caching, however it will go via the passthrough. Allows you to shape the traffic easily at the firewall, but equally - doesn't identify that traffic as being for a specific user.
- We still have issues with Steam content servers and slicing that we need to resolve, this is the cause of the some of the errors causing Steam to failback and this just masks that issue.

Overall it's something I think we should include, but we should not prevent this from continuing to investigate the slicing issues with Steam.

**Comment by DuzAwe** [comment]
I manually set these domains in Pi-Hole, which has resolved my issues. Why not just roll back the previous removal of the Steam domains instead of creating a failover? It would reduce points of failure.

**Comment by mintopia** [comment]
The failover isn't anything to do with us - it's how Steam works. By having it as a separate CDN in cache-domains, it allows those who don't want to intercept all Steam domains to easily disable them.

The actual behaviour of it within lancache itself doesn't matter - Steam is detected based on User Agent, not the cache domains CDN definitions.

**Comment by DuzAwe** [comment]
I see. Made an assumption and was wrong.
I have run this locally without issue and integrated it with my Pi-Hole set-up no issues seen.

**Comment by mintopia** [comment]
Valve have fixed this issue in the latest Steam Client. It no-longer forgets the lancache. Closing as we don't need this anymore.

**Pull request closed without merging**
