### PR TITLE
feat: add support for debian based repos

### PR DESCRIPTION
**Pull request by dgibbs64**
### What CDN does this PR relate to

Popular Debian based repos

* Debian
* Ubuntu
* Kali
* Mint
* Pop_OS!
* Deepin
* ppa launchpad

### Does this require running via sniproxy

untested

### Capture method

repo list is available in distro sources.list

### Testing Scenario

home. Added the records and ran apt update; apt upgrade and watched lancache logs to ensure caching happened.

I confirmed that caching happened

### Testing Configuration
```
<!-- Paste either your docker run command from the DNS container OR explain how you have setup DNS zone files etc to test this issue -->
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

### CODE REVIEW

**Comment by MathewBurnett** [comment]
We are unlikely to add Linux repos as upgrading Linux is not a core feature required by LAN. I would look at apt-cacher-ng, which is a proxy designed to do this which understands the shap of Linux repos.

**Comment by dgibbs64** [comment]
I would suggest otherwise. Linux gaming is growing with the addition of proton. Windows has [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) now that supports Ubuntu and Debian. SteamDeck is a Linux-based game console (adding support would be useful (I think its arch based?). Game servers (using SteamCMD) that run on Linux etc. 

To me, this is no different that supporting Windows Updates which is currently supported by LAN cache.

**Comment by dgibbs64** [comment]
For my personal use case, I am developing a new docker container for my game server project [LinuxGSM](https://linuxgsm.com) (That was first developed at a Multiplay LAN event) which requires repeated access to update Ubuntu. Adding this is greatly speeding up the development of the docker containers.  Debian-based distros are also by far the most popular distros for hosting game servers. So to me from a game server perspective this is very useful.

I hope I have highlighted how useful this is for gamers and game server hosters. 😃

**Comment by MathewBurnett** [comment]
Windows support is really a side consequence of supporting game purchase through the Microsoft store. While I accept that more people have access to Linux. It's still an overwhelming large windows market at LAN.

**Comment by Zakarot** [comment]
I'd also love to see this added. Perhaps it doesn't make so much sense in a LAN-party setting, but it certainly does for the "home setup with multiple gamers." And seeing that LANCache runs in docker, anyone using this is sure to have at LEAST one Linux host.

**Comment by zunder1990** [comment]
I am in support of adding this. We use lancache at our lan party which is a sub event of the SouthEast Linux Fest. It is not uncommon to have 300-400 linux based computers using the network at an given time.

**Comment by DuzAwe** [comment]
I’d also add to the pile. That with two steam decks in the house now that
caching Linux would be useful.

**Comment by dgibbs64** [comment]
@DuzAwe SteamDeck updates would be a good addition. I believe it is arch-based and I have no experience in that distro. Hopefully it is possible to cache updates like Debian based distros

**Comment by dgibbs64** [comment]
Looks like it's possible to cache packages using Squid. So I am assuming it wouldn't be a stretch to support pacman
Squid
https://wiki.archlinux.org/title/Package_Proxy_Cache
Nginx
https://fernandobarillas.com/blog/2017/caching-pacman-packages-with-nginx/

**Comment by MathewBurnett** [comment]
> We are unlikely to add Linux repos as upgrading Linux is not a core feature required by LAN. I would look at apt-cacher-ng, which is a proxy designed to do this which understands the shap of Linux repos.

If someone wants to maintain a fork that includes them it should work. However the current thinking our side is that we are not going to include them in the main list.

**Comment by dgibbs64** [comment]
I will setup an action to check the main repo to make sure it gets updates.

**Comment by redtrillix** [comment]
Oh, I didn't see this: https://github.com/uklans/cache-domains/pull/208/commits/54ee3311bc111779a4a0b10b709b8a61352fe44b.
I've changed my fork to only include http domains, I can revert my changes and close my PR if you want (I wasn't sure if uklans/repo wanted both https and http, or just the http domains).

**Comment by redtrillix** [comment]
It could also be worth adding the kernel to the Linux kernel to the list.
I think these should be the correct domains:
```
mirrors.kernel.org
git.kernel.org
cdn.kernel.org
```

I could be wrong though, and/or it might not be a good idea to add these, lmk what you think.

**Comment by GamerKingFaiz** [comment]
> We are unlikely to add Linux repos as upgrading Linux is not a core feature required by LAN. I would look at apt-cacher-ng, which is a proxy designed to do this which understands the shap of Linux repos.

Is there a downside to adding more domains to this repo?

**Comment by VibroAxe** [comment]
Yes, unfortunately debian does not follow the immutability rule which lancache is built on, so adding these to a cache can result in broken package files. 

There's is nothing to stop you maintaining your own list with this in however and still using the lancache toolset or others.

**Pull request closed without merging**
