### PR TITLE
Update nintendo.txt for Wii U downloads

### PR DESCRIPTION
**Pull request by some-username-here1**
Added web addresses for LAN Cache support for the Nintendo Wii U, Logged and noted from Wireshark, also minor re-organization of web addresses

### What CDN does this PR relate to
Nintendo, the Wii U specifically. (or #68 it meant?)

Have tested with Mario Kart 8 DLC and a few Virtual Console games, so far

### Does this require running via sniproxy
Untested, currently.

### Capture method
Wireshark

### Testing Scenario
Custom branch (local-testing) of forked steamcache-dns, seperate steamcache-* container

Apologies for re-creating this, I'm new to doing this stuff

### CODE REVIEW

**Comment by some-username-here1** [comment]
With a bunch of addresses being more or less from the subdomain:
```
ninja.wup.shop.nintendo.net
ninja.wup.eshop.nintendo.net
tagaya.wup.shop.nintendo.net
tagaya.wup.eshop.nintendo.net
aqua.hac.lp1.d4c.nintendo.net
atum.hac.lp1.d4c.nintendo.net
bugyo.hac.lp1.eshop.nintendo.net
pushmo.hac.lp1.eshop.nintendo.net
tagaya.hac.lp1.eshop.nintendo.net
```

Is safe to merge all of them down to `*.hac.lp1.eshop.nintendo.net`, `*.hac.lp1.d4c.nintendo.net`, `*.wup.shop.nintendo.net` and `*.wup.eshop.nintendo.net`?

**Comment by VibroAxe** [comment]
My concern is if these domains are http or https. We do not want to randomly assign dynamic content to the cache, only the final download and then only if it is coming from an http depot. In the wireshark capture can you see the http download coming from these domains?

**Comment by some-username-here1** [comment]
Would providing the multiple packet captures I have help? just make sure to search for `shop.nintendo.net` and have `!ipv6 && !arp` filters (since the Wii U doesn't use IPv6, only Ipv4)

**Comment by some-username-here1** [comment]
Also I found a couple of more addresses, which is helping out

**Comment by some-username-here1** [comment]
I've tested my custom branch with my branched fork of steamcache-dns, and the only url the Wii U was hitting was `ccs.cdn.wup.shop.nintendo.net` while downloading my games, them being Mario Kart 8 DLC, Paper Mario, TLoZ: Link to the Past, and Kirby Super Star

Here's the log, by the way:
[access.log](https://github.com/uklans/cache-domains/files/3052115/access.log)

**Comment by VibroAxe** [comment]
Thanks for this

**Pull request merged**
