### PR TITLE
Update to scripts

### PR DESCRIPTION
**Pull request by Mikki-10**
Hi

I have made an CLI mode but kept web mode for other for other purposes if needed, we can remove the mode if you do not like it.

I have made a template so it shoud be easier to add more dns services.

I have also added some categories to the txt files to support to have all games in one or updates, and to filter SPI proxy domains.

Let me know what you think and i will be happy to answer what question you might have about the script.

### CODE REVIEW

**Comment by Mikki-10** [comment]
Sry i can see that it came in a new pull request.

**Comment by Mikki-10** [comment]
I forgot to add support input parameters for automated scripting, i wil do that in a later version

**Comment by VibroAxe** [comment]
Hi Mikki,

I've only done a partial review the code, but here's my initial comments. These need solving before we proceed with the pull. 

1) any metadata (the categories) should be held in the json file, not comments in the .txt files. 
2) As I mentioned last time, one server ip cannot host all of the cache domains, you require one IP per cdn service or you will have cache collisions. I'm not sure how best to add in the IP address, probably best to prompt per service based on your current setup.
3) Code layout is nice, good idea in principal, well implemented

**Comment by Mikki-10** [comment]
1. Okay i will look in the json file for categories instead
2. Okay i will update the code to support the correct setup (figure out how to do so) :)
3. Thanks

**Comment by Mikki-10** [comment]
Hi
Here is an update, it now support arguments for automation and the support for individual cache server ip's, read the readme for information about how.
(Web part not updated yet, happens in a later pull request)

**Comment by Mikki-10** [comment]
Forgot to move the function when all dns records is wanted.

"Moving service type "A" into the logic with the others, to support the new $services_out format and individual cache server ip's"

**Comment by VibroAxe** [comment]
Hi Mikki

I've been thinking about how best to handle this and I don't think we want the additional effort of maintaining the script as part of the domains repo. If you want to run your own repo which provides this functionality, i'd be more than happy to add a note in the readme to point people in your direction, however our recommended use case will always be steamcache/steamcache-dns

**Pull request closed without merging**
