### PR TITLE
More cachable apple targets

### PR DESCRIPTION
**Pull request by aanon4**
### What CDN does this PR relate to

Update apple.txt with new targets.
### Does this require running via sniproxy

No.
### Capture method

Ran while updating OSX and iOS devices and observing traffic using ntopng.
### Testing Scenario

Home lan through pfSense.
### Testing Configuration
```
N/A
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
      2 cp801-prod.do.dsp.mp.microsoft.com
      2 fe2.update.microsoft.com
      2 geo-prod.do.dsp.mp.microsoft.com
      2 kv801-prod.do.dsp.mp.microsoft.com
      6 media.forgecdn.net
      2 officecdn.microsoft.com
     16 receive-lp1.dg.srv.nintendo.net
   5730 river.data.ea.com
      6 sls.update.microsoft.com
      7 steamcdn-a.akamaihd.net
```

### CODE REVIEW

**Comment by VibroAxe** [comment]
Hi there

Assuming you have implemented this in your own lancache infrastructure, can you confirm that you have an sniproxy running on these domains and are seeing no hits?

We need to ensure if these are viable cache targets for http caching

**Comment by aanon4** [comment]
I updated my original comment with the missing sniproxy info.

**Comment by VibroAxe** [comment]
I think we need to have a think amongst the group about what we want to cache within some of these files. We don't typically see a lot of ios update traffic at a lan gaming event.

@mintopia @Lepidopterist thoughts?

**Comment by aanon4** [comment]
Fair enough - I'm using this as a general cache as well as just for games; obviously not the same use case.

**Comment by VibroAxe** [comment]
Thanks very much for the PR, but on this occasion we've decided not to add the extra domains. This is primarily for bulk caching of gaming cdns and we don't have a reliable way to test these extra domains on a regular basis. Given the intended audience I doubt we would see a large ammount of traffic to them anyway.

Thanks for your help though!

**Pull request closed without merging**
