### PR TITLE
wargaming.net.txt: add 3 new domains

### PR DESCRIPTION
**Pull request by rotanid**
### What CDN does this PR relate to
Add 3 new War Gaming CDNs

### Does this require running via sniproxy
no change

### Capture method
tbc

### Testing Scenario / Configuration
We used the docker-compose setup on an event with about 1.200 attendees in Neumünster/Germany.
our DNS setup is based on BIND

### CODE REVIEW

**Comment by VibroAxe** [comment]
Hi @rotanid 

Thanks for the PR, Can you please fill out the merge template. I'm particularly interested in seeing the capture method and testing bits before we merge.

### What CDN does this PR relate to


### Does this require running via sniproxy


### Capture method


### Testing Scenario


### Testing Configuration
```
<!-- Paste either your docker run command from the DNS container OR explain how you have setup DNS zone files etc to test this issue -->
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

**Comment by rotanid** [comment]
sorry, the event i used this on is over and i won't have the chance to test things for a year now.
feel free to close my PR if you don't want the contribution under these circumstances.

**Comment by VibroAxe** [comment]
@rotanid quite happy to take the PR, just tell us what you did to test it, how many people etc ;P

If you don't have the sniproxy output thats fine, leave that bit blank

**Comment by rotanid** [comment]
so the first part of the PR are simply two typo fixes, there is no DNS record "dl.wargaming.net" but only "dl1.wargaming.net", and "wargaming.net.edgesuite.ne" also does not exist - but i just noticed that correcting it doesn't change anything as "wargaming.net.edgesuite.net" also does not exist :-D

i just updated this PR to only include the additional domain names and put the fixes in a separate PR #47

we used the docker-compose setup on an event with about 1.200 attendees in Neumünster/Germany.
our DNS setup is based on BIND

**Comment by VibroAxe** [comment]
OOI, where did you find the new domains from? Wireshark or bind logs?

**Comment by rotanid** [comment]
looking at our git they seem to have been included at a smaller event on which i wasn't present, so: sorry, i don't know - and i can't look up logs of the recent event anymore, too...

**Comment by VibroAxe** [comment]
Sorry @rotanid I forgot this one over christmas, All merged! 👍

**Pull request merged**
