### PR TITLE
New blizzard domain

### PR DESCRIPTION
**Pull request by picchioni**
The lancache folks discovered a new domain for blizzard, pushing upstream.

### CODE REVIEW

**Comment by VibroAxe** [comment]
Hi picchioni

Thanks for the pr, two questions 
1) which "lancache guys"
2) can you confirm where this has been tested

**Comment by VibroAxe** [comment]
Answering my own question 1 --> Reference: https://github.com/bntjah/lancache/issues/110

**Comment by picchioni** [comment]
For question 2, Here's a screenshot of a pcap I took if that helps (attempted to download Starcraft 2). I can provide an actual pcap if you'd like
screen shot 2018-09-16 at 9 37 51 pm
screen shot 2018-09-16 at 9 45 00 pm

**Comment by VibroAxe** [comment]
It's more assurance that it doesn't break anything on other systems. If you've only tested this on a local install then we need a larger sample size to ensure there's nothing breaking in it!

**Comment by picchioni** [comment]
Agreed, a sample size of 1 isn't a representation. I just tested in my lab setup, but not on anything in larger scale.

**Comment by Volkor3-16** [comment]
Tested on my network, adding this domain to my local unbound, and now blizzard games are being passed through my cache

**Comment by 8073421Robotsonic** [comment]
First post and have no idea what i'm doing but hope this helps.  You can check your Agent log files in the Battle.net Agent directory.  It looks like everything from 137.221.64.1 up to .8 is under both http and https for us.cdn.blizzard.com

Here is as copy past from one of the logs after downloading starcraft 2:
`[I 2018-10-02 22:36:38.0712] {2d4c} INF: adding network address 137.221.64.1:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0712] {2d4c} INF: adding network address 137.221.64.2:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0712] {2d4c} INF: adding network address 137.221.64.3:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0713] {2d4c} INF: adding network address 137.221.64.4:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0713] {2d4c} INF: adding network address 137.221.64.5:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0713] {2d4c} INF: adding network address 137.221.64.6:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0714] {2d4c} INF: adding network address 137.221.64.7:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0714] {2d4c} INF: adding network address 137.221.64.8:80 for server http://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0714] {2d4c} INF: adding network address 137.221.64.1:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0715] {2d4c} INF: adding network address 137.221.64.2:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0715] {2d4c} INF: adding network address 137.221.64.3:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0715] {2d4c} INF: adding network address 137.221.64.4:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0716] {2d4c} INF: adding network address 137.221.64.5:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0716] {2d4c} INF: adding network address 137.221.64.6:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0716] {2d4c} INF: adding network address 137.221.64.7:443 for server https://us.cdn.blizzard.com/
[I 2018-10-02 22:36:38.0717] {2d4c} INF: adding network address 137.221.64.8:443 for server https://us.cdn.blizzard.com/`

**Comment by VibroAxe** [comment]
Works for me, thanks for the testing all

**Pull request merged**
