### PR TITLE
Rename epic-games.txt to epicgames.txt

### PR DESCRIPTION
**Pull request by Crabbey**
### What CDN does this PR relate to
epicgames

### Does this require running via sniproxy
N/A

### Capture method
N/A

### Testing Scenario
N/A

### Testing Configuration
N/A

### Sniproxy output
N/A

### CODE REVIEW

**Comment by some-username-here1** [comment]
on top of that, can the Epic Games service name be renamed from `EPIC-GAMES` to `EPICGAMES` instead?

**Comment by nightah** [comment]
@VibroAxe sorry don't mean to be annoying but if we could please get this merged ASAP.
https://github.com/uklans/cache-domains/commit/bfcadf481ddf723d3131809039f0be9b15861f93
Was a breaking change for the update scripts per the discussion on that commit, this PR resolves that issue.

**Comment by VibroAxe** [comment]
@nightah merged

**Comment by nightah** [comment]
Champion, thanks @VibroAxe.

**Pull request merged**
