### PR TITLE
Remove all Steam domains except lancache.steamcontent.com

### PR DESCRIPTION
**Pull request by VibroAxe**
### What CDN does this PR relate to
Removing all steam domains except for the lancache.steamcontent.com trigger domain

### Does this require running via sniproxy
Yes

### Capture method
Conversations with valve devs

### Relevant PR's
#124 - Originally reverted due to issue with the steam-for-linux client, see valve issue below
#162 - Reverted 124 due to issues
https://github.com/ValveSoftware/steam-for-linux/issues/7514 - Issue identified within steam-for-linux

### Steam for linux workaround
If the steam-for-linux client is operating in an environment with IPV6 disabled it needs to be reenable at both machine and interface level. The ipv6 address does not need to be configured. Hopefully valve will fix this in due course. In the mean time this would resolve https://github.com/lancachenet/monolithic/issues/141

### CODE REVIEW

**Comment by mintopia** [comment]
It's a yes from me.

**Review by mintopia — APPROVED** [review]

**Comment by VibroAxe** [comment]
@Lepidopterist @MathewBurnett @unspec still waiting on your review comments

**Review by Lepidopterist — APPROVED** [review]

**Comment by nightah** [comment]
I also think the IPv6 issue will be less of a problem when we actually introduce IPv6 support.

I can put aside some time to finalise some changes and start prototyping IPv6 support (I've had it working before) that way our general guideline of "making sure IPv6 is turned off" doesn't really need to be mandated.

**Review by unspec — APPROVED** [review]

**Comment by IIPoliII** [comment]
Actually if you resume a download steam will not pass by lancache.steamcontent.com it will go simply on a content server so the cache isn't applied anymore...

**Pull request merged**
