### PR TITLE
Update riot.txt

### PR DESCRIPTION
**Pull request by nyemenzo**
im using garena to play LOL by riot. the normal cdn dont cache anything. i run wireshark and find that host. can you add this please so that i can cache lol using garena.

### What CDN does this PR relate to
riot

### Capture method
wireshark

### CODE REVIEW

**Comment by VibroAxe** [comment]
@nyemenzo I think that garena should be split out into a new file / cdn entry -> "garena"
If you can update this pr to that i'd happily merge it

**Comment by nyemenzo** [comment]
@VibroAxe im now separating LOL from riot.txt to garena.txt but everyting that it cache is a MISS. no matter how much i retry there is no HIT.

**Comment by VibroAxe** [comment]
can you send us some of your logs

**Comment by nyemenzo** [comment]
here is my access log and error of garena
[access.log](https://github.com/uklans/cache-domains/files/2877681/access.log)
[error.log](https://github.com/uklans/cache-domains/files/2877682/error.log)

**Comment by VibroAxe** [comment]
This would need to be a seperate garena cdn not an additional list for riot

**Pull request closed without merging**
