### PR TITLE
Battle State Games, DNS records currently known to me.

### PR DESCRIPTION
**Pull request by DeusQain**
The game does a DNS request for a single domain that is a CNAME for the CDN domain names.

### What CDN does this PR relate to

Battle State Games Launcher for Escape from Tarkov
### Does this require running via sniproxy

untested
### Capture method
wireshark on the machine downloading, and packet capture at the edge devices, and DNS logs on the DNS servers.

### Testing Scenario

I set this up and tested it at Dreamhack Anaheim.
Primed the cache with a test, and multiple users downloaded during the event.

### Testing Configuration
DNS Zone file used the entries from this commit to point to the cache.
NGINX used the first line, and wild carded the rest.
### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
SNI Proxy I'm running doesn't have logs pertaining to this.
```

### CODE REVIEW

**Comment by MathewBurnett** [comment]
`nslookup cl-453343cd.gcdn.co
Non-authoritative answer:
cl-453343cd.gcdn.co     canonical name = d.gcdn.co.
Name:   d.gcdn.co
Address: 92.223.58.254`

Where I am it looks like cl-453343cd.gcdn.co (and cdn-11.eft-store.com) all have the cname d.gcdn.co was that the same state side? 

I'm wondering if d.gcdn is too broad? also na.a.gcdn.co could be a similar case?

**Comment by DeusQain** [comment]
That's what I have seen.  Everything seems to be a CNAME back to d.gcdn.co 
I dug around some forums, and some folks found that Asia has different domain names.  But the game itself seems to originally poke at cdn-11.eft-store.com. To initiate the download.
I had those DNS records in my zone files.

NGINX I had cdn-11.eft-store.com, and *.gcdn.co  and it worked without much incident.

**Comment by MathewBurnett** [comment]
I think if you remove d.gcdn.co and na.a.gcdn.co please @DeusQain  then we add the most specific ones and look to add any more that we learn as we go. I'd rather not cache the root as their could be anything in that cdn

**Comment by DeusQain** [comment]
That's a valid point. 

Next event I'm at, I'll have access to someone who has the game.
But I agree, for now I'll remove those lines.

**Comment by unspec** [comment]
Probably need a corresponding update to cache_domains.json for this, as its a new CDN?

**Comment by DeusQain** [comment]
Updated, and created new pull-request before I thought about just adding more to this.

**Comment by MathewBurnett** [comment]
#134 now merged

**Pull request merged**
