### PR TITLE
New steam content domain

### PR DESCRIPTION
**Pull request by JasonRivers**
Valve have added more another content domain

### CODE REVIEW

**Comment by JasonRivers** [comment]
Don't merge this one yet, I'm still testing.

**Comment by JasonRivers** [comment]
I don't think this domain is used for depot downloads, otherwise i63 would have noticed!

**Comment by sirsquidness** [comment]
It looks like my Steam client is only using these *.cm.steampowered.com addresses for not-HTTP connections on port 27021. You definitely do not want to hijack these domains and point them to a HTTP cache, as Steam will break a lot. 

The hostnames it is resolving appear in `config.vdf` as a list under the key `CMWS`. These connections are TLS connections, and I'm going to take a wild stab in the dark and say that CMWS probably stands for `Content Master <something> Secure` ... maybe web or websocket? idk, doesn't matter. The point is .... definitely don't hijack these :ok_hand:

**Comment by Celant** [comment]
Hey all, @sirsquidness is right *.cm.steampowered.com is the connection manager servers for Steam, which handle logins and other stuff.

**Pull request closed without merging**
