### PR TITLE
Re-add minecraft.txt for Minecraft

### PR DESCRIPTION
**Pull request by some-username-here1**
### What CDN does this PR relate to
A previously available CDN before it was deleted without a valid reasoning.

### Does this require running via sniproxy
N/A (does it mean a "No" if you can download the files via http anyway?)

### Capture method
Via the minecraft launcher log

### Testing Configuration
```
<!-- Paste either your docker run command from the DNS container OR explain how you have setup DNS zone files etc to test this issue -->
```

### CODE REVIEW

**Comment by Lepidopterist** [comment]
Mionecraft is now https ( as per #45 ) and not cacheable.  Please provide evidence this is incorrect, and we will update.

**Comment by some-username-here1** [comment]
Is this still appliable as evidence? (all being linked via http)

### `launchermeta.mojang.com`
[pre-1.6.json](http://launchermeta.mojang.com/v1/packages/4759bad2824e419da9db32861fcdc3a274336532/pre-1.6.json)
[1.9.json](http://launchermeta.mojang.com/v1/packages/06cc9a2c5ce504dc712ea2f699e4d645c48416dd/1.9.json)
[1.13.1.json](http://launchermeta.mojang.com/v1/packages/6d78d53da5ac7158e2f725056312edf9871dfbb1/1.13.1.json)
### `launcher.mojang.com`
[client.jar (1.3.2)](https://launcher.mojang.com/v1/objects/c2efd57c7001ddf505ca534e54abf3d006e48309/client.jar)
[client.jar (1.9)](http://launcher.mojang.com/v1/objects/2f67dfe8953299440d1902f9124f0f2c3a2c940f/client.jar)
[`client-1.7.xml` is forced through https, so it's kinda divided here](http://launcher.mojang.com/v1/objects/6605d632a2399010c0085d3e4da58974d62ccdfe/client-1.7.xml)

### `resources.download.minecraft.net`
[asset object 1](http://resources.download.minecraft.net/bd/bdf48ef6b5d0d23bbb02e17d04865216179f510a)
[asset object 2](http://resources.download.minecraft.net/92/92750c5f93c312ba9ab413d546f32190c56d6f1f)
[asset object 3](http://resources.download.minecraft.net/45/45b1f0a2429a5aab49cb628078569466377cfcb0)
[asset object 4](http://resources.download.minecraft.net/29/29a8624f1227f25db78ae62fcc8d151a63330946)
[asset object 5 ](http://resources.download.minecraft.net/b5/b59255b3bad3d31fbf64b2c6c674669663df0fed)
[asset object 6](http://resources.download.minecraft.net/3b/3ba59f91eb84357244a47873c0b07a43dd41f53f)

I've tested these through my web browser, so I didn't mean to provide invalid evidence if it's handled a different way. 
Also I couldn't test `libraries.minecraft.net` as that returned a 403 "Bad request." Error either way (http or https)

**Comment by some-username-here1** [comment]
Or is this all invalid with the Minecraft Launcher going through https?
since I do want to try to redirect https to http for this, when possible

**Comment by VibroAxe** [comment]
@some-username-here1 I'm happy to merge this, you've done a good investigative job. Thanks

Can you please mark this as ready for review so we can continue

**Comment by some-username-here1** [comment]
With `libraries.minecraft.net` and `resources.minecraft.net` being included? Though that can be tested and then the file can be changed on feedback with what's the log (and access log) is outputting...

**Comment by VibroAxe** [comment]
if libraries.minecraft at least returns 403 on http that means it's listening, we can merge it so you can test it properly with steamcache-dns, if it doesn't work I can revert it back

**Comment by some-username-here1** [comment]
Alright!

**Comment by VibroAxe** [comment]
@some-username-here1 let me know if you have any issues

**Comment by some-username-here1** [comment]
Since it's now been merged, is there a way to update my current containers so that the minecraft service can be added, or I don't need to?

**Comment by VibroAxe** [comment]
aye, restarting the containers should pull the latest list

**Comment by some-username-here1** [comment]
Should I be concerned that the access.log isn't outputting anything? with using `tail -f`, or should I just wait for a while for it to go into effect?

Note: Nevermind, I looked into the log for my steamcache-dns container and it's looping with UPSTREAMDNS not having a `;` in-between the IPv4 Addresses, will update once that's fixed

**Pull request merged**
