### PR TITLE
Added Adobe CDN, Google CDN and new Apple CDN domains

### PR DESCRIPTION
**Pull request by TheBinaryLoop**
### What CDN does this PR relate to
New Adobe CDN
New Google CDN
Extended Apple CDN

### Does this require running via sniproxy
Untested

### Capture method
Found at another lancache project
https://github.com/tsvcathed/nginx_lancache

### Testing Scenario
Home and small lan

### Testing Configuration
1. Created dnsmasq conf files using the script.
2. Setup pihole to use these conf files

### Sniproxy output
None

### CODE REVIEW

**Comment by Lepidopterist** [comment]
Thanks for the submission,

I'm going to put this on hold until the end of November so we can test in a live environment.

The origin repo does look encouraging though.

**Comment by MathewBurnett** [comment]
Started looking at the adobe stuff. As far as i can determine everything from creative cloud is all HTTPS. Do you have anything you have found on HTTP @TheBinaryLoop ?

**Comment by TheBinaryLoop** [comment]
No. It worked sometimes and sometimes not. I don't know why. But the other cdns work.

**Comment by MathewBurnett** [comment]
Do you have any obvious test cases for apple or google? I'm playing with them now

**Comment by TheBinaryLoop** [comment]
I used the Apple Product Updater for Windows to test the apple cdn.

**Comment by MathewBurnett** [comment]
So having looked into the adobe CC and discovered it's HTTPS and seen the other two are for smallish non-gaming apps I am inclined to close this. There may be some items that would be well served by squid caching for example. 

After some brief discussion the root logic we are using is that the chance of a HIT at a LAN compared with the amount of traffic the SNI-Proxy would have to exclude makes this a poor candidate. However your clear submission and quick replies are much appreciated.

**Pull request closed without merging**
