### PR TITLE
New windows update dns

### PR DESCRIPTION
**Pull request by antoinelochet**
Here are the relevant logs:
`31-Aug-2018 20:07:05.832 client @0x56282ce28360 192.168.1.107#56301 (fe2.update.microsoft.com): query: fe2.update.microsoft.com IN A + (172.17.0.3)
31-Aug-2018 20:07:08.601 client @0x56282d362a40 192.168.1.107#51690 (tlu.dl.delivery.mp.microsoft.com): query: tlu.dl.delivery.mp.microsoft.com IN A + (172.17.0.3)
31-Aug-2018 20:07:08.611 client @0x56282d362a40 192.168.1.107#53391 (array614-prod.do.dsp.mp.microsoft.com): query: array614-prod.do.dsp.mp.microsoft.com IN A + (172.17.0.3)
31-Aug-2018 20:07:08.999 client @0x56282d2e7a20 192.168.1.107#63020 (disc601-prod.do.dsp.mp.microsoft.com): query: disc601-prod.do.dsp.mp.microsoft.com IN A + (172.17.0.3)
`

### CODE REVIEW

**Comment by VibroAxe** [comment]
Do we know that this doesn't generate any adverse affects. Has it been tested at a LAN and if so which?

**Comment by antoinelochet** [comment]
This has been running on the three computers on my local network for 2 weeks now.
No problem so far

**Comment by VibroAxe** [comment]
@antoinelochet thanks for this, next time can you try and ensure that you don't end up with 12 commits to change 3 lines ;)

Squashed and merged

**Comment by VibroAxe** [comment]
@antoinelochet  Could you also confirm if you are using sniproxy in this install and seeing any https traffic on those domain names?

**Comment by antoinelochet** [comment]
Yes, I am using sniproxy
And sorry for the squashing, I intended tondo it but I forgot :(

**Comment by VibroAxe** [comment]
Are you able to run the following command on your docker host for us

`docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | grep microsoft | sort | uniq -c` and post the output

**Comment by antoinelochet** [comment]
Here you are:

```
antoine@server-nuc-1:~$ docker logs sniproxy | sed 's/.*\:443 \[//;s/\].*//' | grep microsoft | sort | uniq -c
     65 cp601-prod.do.dsp.mp.microsoft.com
      1 fe2.update.microsoft.com
      1 geo-prod.do.dsp.mp.microsoft.com
      1 geover-prod.do.dsp.mp.microsoft.com
      1 kv601-prod.do.dsp.mp.microsoft.com
      4 sls.update.microsoft.com
```

**Pull request merged**
