### PR TITLE
Revert steam DNS list to being "complete"

### PR DESCRIPTION
**Pull request by Travis-Snoozy**
At time of writing, the Steam client for Windows (Mar 24 2023, at 10:12:43; 1679680416), Linux (Mar 24 2023, at 17:20:43; 1679680416), and the Steamdeck do not respect lancache.steamcontent.com any longer. Revert this list so that those clients actually use the cache, instead of bypassing it.

### What CDN does this PR relate to
Steam

### Does this require running via sniproxy
Untested

### Capture method
N/A (reverting to previous values)

### Testing Scenario
Home with 4 Windows steam clients, 1 Steamdeck, 1 Linux steam client. None are accessing the cache per `tail -f` of the access log (the cache and DNS are both working, because WSUS log entries are showing for all the Windows machines). Disabling the new Steam share-on-LAN feature for the endpoints, deleting and re-installing a small game (Papers, Please) hits the WAN directly, and not the cache. On a Windows client, flushing the DNS cache, reinstalling the game, and then dumping the DNS cache shows that the client did not even reference lancache.steamcontent.com, but instead went directly to the CDN addresses.

### Testing Configuration
For the current (broken) state: OpenWRT router running cache-domains-wolfssl, which pulls the uklans/cache-domains repository and auto-generates the dnsmasq configuration. OpenWRT has been configured to block all direct LAN-to-WAN DNS lookups, so the router is the only entity able to resolve DNS traffic on the LAN. [With an exception in the rule to permit the lancache server to do direct queries.]

The nominal fix is to revert the prior change that removed all the CDN entries, leaving only lancache.steamcontent.com. Additional changes to the DNS list may be necessary beyond this simple reversion to ensure capture of all the CDN DNS values Steam now uses.

### Sniproxy output
N/A

### CODE REVIEW

**Comment by Travis-Snoozy** [comment]
I have confirmed (via CACHE_DOMAINS_REPO on the monolithic docker, and CACHE_DOMAINS_SRC via the OpenWRT dnsmasq generation script), when pointed at uklans/cache-domains github repository, Steam is not directed to the cache (WAN activity, no log entries in activity.log). When pointed to my own repo, with the steam.txt list reverted, traffic is routed through the cache, and both cache hits and misses are logged.

**Comment by mintopia** [comment]
I can't reproduce this on Windows on the same Steam version. Checking `content_log.txt` it shows the expected output:

```
[2023-03-25 20:49:47] Enabling local content cache at '::ffff:c0a8:b' from lookup of lancache.steamcontent.com.
[2023-03-25 20:49:47] Adding cache type 'LANCache' on host '::ffff:c0a8:b'
```

The lancache server access.log also shows the requests going through to it:

```
[steam] 192.168.0.206 / - - - [25/Mar/2023:20:50:36 +0000] "GET /depot/1649081/chunk/4c08deb04a0dba1fcc81d3ab9b133a8ff16e18c9 HTTP/1.1" 200 987312 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache2-lhr1.steamcontent.com" "-"
[steam] 192.168.0.206 / - - - [25/Mar/2023:20:50:36 +0000] "GET /depot/1649081/chunk/1cefcbf96c5894e1cc05b75e797393e6cbf74f59 HTTP/1.1" 200 644512 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache2-lhr1.steamcontent.com" "-"
[steam] 192.168.0.206 / - - - [25/Mar/2023:20:50:37 +0000] "GET /depot/1649081/chunk/725a3bb06c7d7558efaf23a89f1dc3208a0ea83f HTTP/1.1" 200 639568 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache2-lhr1.steamcontent.com" "-"
[steam] 192.168.0.206 / - - - [25/Mar/2023:20:50:37 +0000] "GET /depot/1649081/chunk/eeae52e985945c84523c9b6611864b79a0f7db5b HTTP/1.1" 200 640544 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cache2-lhr1.steamcontent.com" "-"
```

**Comment by GotenXiao** [comment]
Confirming non-reproduction with a Windows client, same Steam version; manually configuring only the `lancache.steamcontent.com` trigger domain with an RFC1918 address, and an IPv6 ULA address.

```
[2023-03-25 14:39:41] Enabling local content cache at 'fd85:d58a:6c4:2::5' from lookup of lancache.steamcontent.com.
[2023-03-25 14:39:41] Adding cache type 'LANCache' on host 'fd85:d58a:6c4:2::5'
```

Could you try reverting back to the default configuration (i.e. without the `CACHE_DOMAINS_REPO`) and verifying what is present in your Steam install's `content_log.txt`?

See also the [Non-RFC1918 IP Ranges](https://lancache.net/docs/common-issues/#non-rfc1918-ip-ranges) section of the common issues page.

**Comment by Travis-Snoozy** [comment]
My site is non-IPv6 enabled (or, rather, transit of IPv6 traffic is explicitly _disabled_ at the router). The reverse ask I have is to block IPv6 traffic transit on your site, and see if this repros in an only-IPv4-routeable context. Certainly, the nslookup from the reproing Windows machine indicates that IPv6 addresses are coming down, even though they are not reachable.

Files attached, local identifying names scrubbed.

[ping6.txt](https://github.com/uklans/cache-domains/files/11070271/ping6.txt)
[nslookup.txt](https://github.com/uklans/cache-domains/files/11070273/nslookup.txt)
[content_log.txt](https://github.com/uklans/cache-domains/files/11070279/content_log.txt)

In the interim, I will see if reconfiguring the DNS resolver on the router to *not* serve (unreachable) IPv6 addresses resolves the issue.

**Comment by Travis-Snoozy** [comment]
Configured the router to return no-answer for lancache.steamcontent.com for AAAA; nslookup now only indicates the 192.168.42.10 IPv4 address. Restarting Steam resulted in the same content_log.txt -- only two local peers noted.

**Comment by Travis-Snoozy** [comment]
Ah, merely starting Steam is insufficient. Actually attempting a download once the AAAA for lancache.steamcontent.com was set to no-answer did route correctly through the cache.

This is not a fault when running through the lancache DNS container -- that seems to correctly return A only, no AAAA.

Not thrilled with this result, don't see a clear line to a great solution to the problem, but it's not _directly_ a bug with lancache.

Thank you!

**Comment by Travis-Snoozy** [comment]
Hmm - well, the Windows clients work now, but the Linux client does not.

[content_log_linux.txt](https://github.com/uklans/cache-domains/files/11070423/content_log_linux.txt)
[nslookup_linux.txt](https://github.com/uklans/cache-domains/files/11070425/nslookup_linux.txt)

**Comment by Travis-Snoozy** [comment]
Ugh. The Linux client is unhappy about receiving :: back from the server, though the Windows client is fine with it.

dnsmasq from the server needs to be configured with local=/lancache.steamcontent.com/ to avoid returning an AAAA record altogether. The dnsmasq config generation script looks like it needs to be fixed up to accommodate that; I'll put together a different PR.

**Pull request closed without merging**
